chore: update README.md
synapseweb3/forcerelay-ckb-contracts pull request #28
Opened 2023-09-19 10:26 UTC by ashuralyk

2023-09-19 14:37 UTC, Flouse requested changes

2023-09-19 14:37 UTC, Flouse commented on README.md
> +This project consists of two CKB contracts serving for `Forcerelay/Eth` and `Forcerelay/Axon` respectively.
```suggestion
This project consists of two types of CKB contracts serving for `Forcerelay/Eth` and `Forcerelay/Axon` respectively.
```

2023-09-19 14:45 UTC, Flouse commented
According to the recent discussion, I renamed this repo to `synapseweb3/crosschain-ckb-contracts`.

2023-09-20 00:58 UTC, ashuralyk commented
> According to the recent discussion, I renamed this repo to `synapseweb3/crosschain-ckb-contracts`.

What about `forcerelay-ckb-contracts`?

2023-09-20 01:48 UTC, Flouse commented
> What about `forcerelay-ckb-contracts`?

changed

2023-09-20 01:48 UTC, Flouse approved these changes

2023-09-20 06:25 UTC, Flouse commented
> What about `forcerelay-ckb-contracts`?

Please change this readme's h1 title too?
https://github.com/synapseweb3/forcerelay-ckb-contracts/pull/28/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1

2023-09-20 08:39 UTC, linnnsss approved these changes

2023-09-20 12:36 UTC, merged